config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: "pages#home"
  resources :gamingsessions, only: [ :index, :show, :create, :update ]

  get "totaux", to: "productions#totaux"

  get "advantages", to: "advantages#advantages"

  get "historique", to: "historics#historique"

  resources :bikes, only: [] do
    get :game, on: :member
  end

  resources :tickets, only: [] do
    resources :purchases, only: :create
  end


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bike.rb
class Bike < ApplicationRecord
  has_many :gamingsessions

  validates :ip_address, presence: true
end

app/models/gamingsession.rb
class Gamingsession < ApplicationRecord
  belongs_to :bike
  belongs_to :user, optional: true

  validates :date, :max_production, :total_production, :session_duration, :score, :bike_id, presence: true
end

app/models/purchase.rb
class Purchase < ApplicationRecord
  belongs_to :ticket
  belongs_to :user
end

app/models/session.rb
class Session < ApplicationRecord
  belongs_to :bike
  belongs_to :user

  validates :date, :max_production, :total_production, :session_duration, :score, :bike_id, presence: true
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  has_many :purchases
  has_many :users, through: :purchases

end

app/models/tip.rb
class Tip < ApplicationRecord
  validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :gamingsessions
  has_many :purchases
  has_many :tickets, through: :purchases

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :first_name, :last_name, :email, presence: true
  validates :email, uniqueness: true
end

app/controllers/advantages_controller.rb
class AdvantagesController < ApplicationController
  def advantage
    @gamingsessions = Gamingsession.where(user: current_user)
    @current_user.wallet = (solde/2)
  end

  private

  def solde_points(gamingsessions)
    solde = 0
    gamingsessions.each do |gs|
      solde += gs.score
    end
    solde
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # demande l'authentification du user dans TOUTES les pages
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?
  # permet de changer les strong params de User en ajoutant first et last name
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :wallet])
  end

  # permet d'arriver sur l'index des gamingsessions après le login
  def after_sign_in_path_for(resource)
    totaux_path
  end
end

app/controllers/bikes_controller.rb
class BikesController < ApplicationController
  # permet de rendre accessible la page bike sans identification
  skip_before_action :authenticate_user!

  # jeu
  def game
  end
end

app/controllers/custom_sessions_controller.rb
class CustomSessionsController < Devise::SessionsController
end

app/controllers/gaming/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authenticate_user!, only: :show
  def index
  end

  def show
  end
end

app/controllers/gamingsessions_controller.rb
class GamingsessionsController < ApplicationController
  # permet d'accéder à show sans login
  skip_before_action :authenticate_user!, only: [:show, :create, :update]

  # affichage de l'index des gamingsessions que de l'user connecté
  def index
    @gamingsessions = current_user.gamingsessions
  end

  def update
    @gamingsession = Gamingsession.find(params[:id])
    @gamingsession.update!(session_params)
  end

  # pdashboard de la gamingsession
  def show
    @gamingsession = Gamingsession.find(params[:id])
    # stock l'id de la gamingsession dans un cookie
    cookies[:gamingsession_id] = @gamingsession.id
    # permet d'avoir les valeurs des records max
    @maxprodsession = Gamingsession.all.order("max_production DESC").limit(1).as_json
    @totalprodsession = Gamingsession.all.order("total_production DESC").limit(1).as_json
  end

  def create
    @gamingsession = Gamingsession.new(session_params.merge({date: Date.today}))
    if @gamingsession.save!
      render json: {svg: svg, url: gamingsession_url(@gamingsession)}
    else
      head :unprocessable_entity
    end
  end

  private

  def svg
    # @qr_code = RQRCode::QRCode.new("http://localhost:3000/gamingsessions/2")
    qr_code = RQRCode::QRCode.new(gamingsession_url(@gamingsession))
    # permet de mettre le qr code en forme carré noir et blanc
    qr_code.as_svg(
      offset: 0,
      color: '000',
      shape_rendering: 'crispEdges',
      module_size: 6,
      viewbox: true
    )
  end

  def session_params
    params.require(:gamingsession).permit(:max_production, :total_production, :session_duration, :score, :bike_id)
  end

end

app/controllers/historics_controller.rb
class HistoricsController < ApplicationController
  def historique
    @gamingsessions = Gamingsession.where(user: current_user)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # permet d'accéder à home sans login
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/productions_controller.rb
class ProductionsController < ApplicationController
  before_action :save_ongoing_gamingsession, only: :totaux

  def totaux
    @gamingsessions = Gamingsession.where(user: current_user)
    @solde = solde_points(@gamingsessions)
    @total_time = total_time(@gamingsessions)
    @total_watt = total_watt(@gamingsessions)
  end

  private

  def solde_points(gamingsessions)
    solde = 0
    gamingsessions.each do |gs|
      solde += gs.score
    end
    solde
  end

  def total_time(gamingsessions)
    total_time = 0
    gamingsessions.each do |gs|
      total_time += gs.session_duration
    end
    total_time = (total_time/60)
  end

  def total_watt(gamingsessions)
    total_watt = 0
    gamingsessions.each do |gs|
      total_watt += gs.total_production
    end
    total_watt = (total_watt.to_f / 7200).round(4)
  end

  def save_ongoing_gamingsession
    # if le cookies avec l'id est présent
    return unless cookies[:gamingsession_id].present?

    @gamingsession = Gamingsession.find(cookies[:gamingsession_id])
    # si la gamingsession appartient déjà à quelqu'un
    if @gamingsession.user_id.present?
      @user = @gamingsession.user

    else
      # si la gamingsession n'appartient à personne
      @user = current_user
      @gamingsession.user = @user
      @gamingsession.save

    end

    @user.wallet += (@gamingsession.score/100)
    @user.save
    cookies.delete(:gamingsession_id)
  end

end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController

  def index
    @purchases = Purchase.where(user: current_user)
  end

  def create
    @ticket = Ticket.find(params[:ticket_id])
    @purchase = Purchase.new(ticket: @ticket, user: current_user)

    return unless current_user.wallet >= @purchase.ticket.price

    if @purchase.save
      current_user.wallet -= @purchase.ticket.price
      current_user.save

      redirect_to advantages_path
    else
      render "index", status: :unprocessable_entity
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def index
  end

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/advantages/advantages.html.erb
<div class="container-tip">
  <div class="title-tip">
    <h1>Le conseil Vel-Watt du jour</h1>
  </div>

  <!--Conseil du jour-->
  <div class="tip-card">
    <div class="Ampoule">
    </div>
    <div class="info-tip">
      <div class="Subject_tip">
        <h2>Éteindre les veilles</h2>
      </div>
      <div class="tip-description">
        <p class="classBatard">Le bon geste : utiliser des multiprises à interrupteur qui permettent de brancher plusieurs appareils et de les éteindre tous en même temps.</p>
      </div>
    </div>
  </div>

  <!--Explication Avantage-->
  <div class="title-avantage">
    <h2>Les avantages Vel-Watt</h2>
  </div>

  <div class="avantages-explication">
    <p>C’est ici que tu pourras voir les offres négociées spécialement pour toi chez nos partenaires et échanger tes Vel-Watt ( VW ) contre des bons de réductions !</p>
  </div>

    <!--Argent Wallet-->
  <div class="score_bloc">
    <% if current_user.wallet == nil  %>
      <h2>Ton solde : 0 VW</h2>
    <% else %>
    <div class="argent">
    </div>
    <div>
      <p>Ton solde</p>
    </div>
    <div>
      <h2><%= current_user.wallet %> VW</h2>
    </div>
    <% end %>
  </div>

  <!--partenaires-->
  <div class="Partenaires">
  <h2>Nos partenaires</h2>
  </div>
  <div class="scroll-avantage-card">
    <div class="carte-avantage">
      <div class="coupon-type">
        <div class="code-promo">
          <p><%= Ticket.first.price %> VW</p>
        </div>
      </div>
      <div class="background-marque"></div>
      <div class="carte-marque">
        <div class="marque-logo">
        <p></p>
        </div>
        <div class="marque-info">
          <div class="marque-name">
          <p><%= Ticket.first.company %></p>
          </div>
          <div class="marque-price">
          <p><%= Ticket.first.content %></p>
          </div>
        </div>
        <div class="plus">
          <%= link_to ticket_purchases_path(Ticket.first.id), data:{turbo_method: :post} do %>
            <i class="fa-solid fa-plus fa-xl plus-vert"></i>
          <% end %>
        </div>
      </div>
    </div>
    <div class="carte-avantage">
      <div class="coupon-type">
        <div class="code-promo">
          <p><%= Ticket.last.price %> VW</p>
        </div>
      </div>
      <div class="background-marque-tree">
        <div class="carte-marque">
          <div class="marque-logo-tree">
          <p></p>
          </div>
          <div class="marque-info">
            <div class="marque-name">
            <p><%= Ticket.last.company %></p>
            </div>
            <div class="marque-price">
            <p><%= Ticket.last.content %></p>
            </div>
          </div>
          <div class="plus">
            <%= link_to ticket_purchases_path(Ticket.last.id), data:{turbo_method: :post} do %>
              <i class="fa-solid fa-plus fa-xl plus-vert"></i>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <div class="carte-avantage">
      <div class="carte-soon">
        <div class="rocket">
        </div>
        <div>
        <h2>Coming</h2>
        <p>De nouveaux partenariats à venir !</p>
        <p>Stay tuned !</p>
        </div>
      </div>
    </div>
  </div>

    <!--Coupons Purchased-->
  <div class="coupons_title">
    <h2>Tes coupons</h2>
  </div>
    <% if Purchase.where(user: current_user) == [] %>
        <p>Tu n'as aucun bon actuellement</p>
    <% else %>
      <div class="scroll-coupons-cards">
        <% Purchase.where(user: current_user).each do |p| %>
          <div class="coupons-card">
            <div class="coupon-marque">
            <p><%= p.ticket.company %></p>
            </div>
            <div class="coupon-contenu">
            <p><%= p.ticket.content %> avec le code :</p>
            </div>
            <div data-controller="coupon"class="coupon-code">
            <p data-coupon-target="coupons" data-action="click->coupons#coupon-code" >X <%= 8.times.map{rand(10)}.join("") %></p>
            </div>
          </div>
        <% end %>
    <% end %>
  </div>
</div>

<%= render "pages/menu" %>
<div class="XXXX"></div>

app/views/bikes/game.html.erb
<div class="gamePages" data-controller="game-three game-animated" data-action="game-session:end->game-config#endSession" data-game-animated-target="pageGame">
  <span data-game-config-url-value="/gamingsessions"></span>
  <div data-controller="game-config timer"
    data-action="game-session:end->game-config#endSession"
    data-game-config-api-value="<%= ENV['FAST_API_ENDPOINT'] %>">
    <div>
      <h2 data-timer-target="timerView" class="compteurTime" data-game-config-target="timeLeft" data-game-animated-target="compteurTime">10:00</h2>
    </div>
    <div class="game--message" data-game-animated-target="gameMessage">
      <svg width="30vw" viewBox="0 0 331 110" fill="none" xmlns="http://www.w3.org/2000/svg">
        <path fill-rule="evenodd" clip-rule="evenodd" d="M331 99.1862V27.4919C331 21.5711 326.2 16.7713 320.279 16.7713H67.0041C93.8057 25.5714 58.6285 94.1609 0 89.4375V99.1862C0 105.107 4.79981 109.907 10.7207 109.907H320.279C326.2 109.907 331 105.107 331 99.1862Z" fill="white"/>
        <path d="M0 89.4375C58.6285 94.1609 93.8057 25.5714 67.0041 16.7713H10.7206C4.7998 16.7713 0 21.5711 0 27.4919V89.4375Z" fill="#A4C5C7"/>
        <path d="M290.988 4.79556C291.846 1.59476 295.136 -0.304732 298.337 0.552919L318.621 5.98812C321.822 6.84577 323.721 10.1358 322.864 13.3366L317.428 33.621C316.571 36.8218 313.281 38.7213 310.08 37.8637L289.796 32.4285C286.595 31.5708 284.695 28.2808 285.553 25.08L290.988 4.79556Z" fill="#FF957E"/>
        <path d="M300.163 18.3109C299.78 19.7407 298.31 20.5892 296.881 20.2061C295.451 19.8229 294.602 18.3533 294.985 16.9235C295.368 15.4938 296.838 14.6453 298.268 15.0284C299.698 15.4115 300.546 16.8811 300.163 18.3109Z" fill="white"/>
        <path d="M307.282 20.2185C306.899 21.6483 305.43 22.4967 304 22.1136C302.57 21.7305 301.721 20.2609 302.105 18.8311C302.488 17.4014 303.957 16.5529 305.387 16.936C306.817 17.3191 307.665 18.7887 307.282 20.2185Z" fill="white"/>
        <path d="M314.402 22.1261C314.019 23.5559 312.549 24.4044 311.119 24.0213C309.689 23.6382 308.841 22.1686 309.224 20.7388C309.607 19.309 311.077 18.4605 312.507 18.8436C313.936 19.2267 314.785 20.6964 314.402 22.1261Z" fill="white"/>
      </svg>
      <div class="game--message--txt">
        <p data-game-animated-target="gameMessageTxt"></p>
      </div>
    </div>
    
    <div class="game--visuel" data-game-animated-target="gameVisuel">
      <div class="game--visuel--total">
        <h3>(Total de production)</h3>
        <p><span data-game-config-target="totalValue" data-game-animated-target="totalValueInfo">0.000 </span>wh</p>
      </div>
      <div class="game--visuel--max">
        <p>Max production :</p>
        <p><span data-game-config-target="maxProduct">0</span> w</p>
      </div>
      <div class="game--visuel--prod">
        <h3>(Production instanté)</h3>
        <p><span data-game-config-target="compteurValue" class="compteur">0 </span>w</p>
      </div>
    </div>
    <div class="QRcodes" data-game-animated-target="QRcodes">
        <div data-game-config-target="svg" class="place"></div>
    </div>
    <span data-action="click->game-config#endSession click->game-animated#end" class="button--game--end" data-game-animated-target="btnEnd">
      <svg width="1vw" viewBox="0 0 12 12" fill="none" xmlns="http://www.w3.org/2000/svg">
        <path d="M11 11L1 1ZM11 1L1 11Z" fill="white"/>
        <path d="M11 11L1 1M11 1L1 11" stroke="white" stroke-width="3" stroke-linecap="round"/>
      </svg>
      <p>STOP</p>
    </span>
    <span data-action="click->game-animated#restart" class="button--game--restart" data-game-animated-target="btnRestart">
      <p>RESTART</p>
    </span>
    <span data-action="click->game-config#initSession click->timer#startTimer click->game-animated#btnStart" class="button--game" data-game-animated-target="btnStart">
      <p>START GAME</p>
    </span>
  </div>
</div>

app/views/gamingsessions/_accueil.html.erb
<h1>Ma production</h1>

<%= current_user.first_name %>

<p>Solde des points :</p>
<p><%= @solde %></p>

<%#  wallet de l'user %>
<p>Wallet = <%=current_user.wallet %> V-W</p>

<%# cumul du temps de toutes les sessions %>
<p>Temps passé : </p>
<p><%= @total_time %> min</p>

<%# cumul de tous les Wh produits %>

<p>Electricité produite</p>
<p><%= @total_watt %>Wh</p>

<p>Explications</p>

<p><%= @total_watt %>Wh = <%= (@total_watt/1000.0).round(4) %> kWh</p>

<p> Que faire avec un 1kWH ?</p>
<p>Allumer une ampoule led pendant 143h</p>
<p>Rouler avec une Renault électrique Zoé pendant 8,5km</p>

<p>Ma production VS la réalité</p>

<p>Vous avez produit de quoi recharger <%=(@total_watt/0.30).round(1) %> fois d'un smartphone </p>

<p>Vous avez produit <%=((@total_watt/1000.0)*100).round(1) %> % de l'énergie necéssaire au cycle d'une machine à laver </p>

<p>Vous avez produit de quoi faire fonctionner un refrigerateur pendant <%=(@total_watt/(548.0/24)).round(1) %> heure(s) </p>

<p>Vous avez produit <%=((@total_watt/21095000.0)*100).round(4) %> % de la consommation de la Tour Eiffel pour une journée </p>

app/views/gamingsessions/_avantage.html.erb
<%# <h1>Le conseil Vel-Watt du jour</h1>

<p>Eteindre les veilles</p>
<p>Le bon geste : utiliser des multiprises à interrupteur qui permettent de brancher plusuers appareils et de les éteindre tous en même temps.</p>

<p>C’est ici que vous pouvez voir les offres négociées spécialement pour vous chez nos partenaires et échanger vos points Vell-Watt ( VW ) contre des bons de réductions !</p>



<p>Wallet =<%=current_user.wallet V-W</p> %>

<%# Ticket.all.each do |ticket| %>
  <%# <p>= ticket.company</p> %>
  <%#= ticket.content %>
  <%#= ticket.price%>
  <%#= button_to "Acheter", ticket_purchases_path(ticket.id) %>
<%# end %>

app/views/gamingsessions/_historique.html.erb
<h1>Historique de vos sessions</h1>

<p><%= @gamingsessions.count %> sessions</p>


<% @gamingsessions.each do |gs| %>
  <p><%= gs.date%></p>
  <p>Prod max<%= gs.max_production%>Wh</p>
  <p>Prod total<%= gs.total_production%>wH</p>
  <p>Score<%= gs.score%></p>
<% end %>

app/views/gamingsessions/index.html.erb
<h1>Sessions#index</h1>
<p>Hello <%= current_user.first_name %></p>

<%= render "pages/menu" %>

app/views/gamingsessions/show.html.erb
<% if current_user %>
<div class="div-espace">
  <h1 > Session du <%= @gamingsession.date.strftime('%d-%m-%Y') %></h1>
</div>
<% else %>
  <div class="db-session-title">
    <h1>Bienvenue sur <br>Vel-Watt !</h1>
  </div>
<% end %>
<h2>Ton score :</h2>


<%#  parti score %>
<div data-controller="quizz-answer" data-quizz-answer-points-value="<%= @gamingsession.score %>">
  <div class="home-card">
    <div class="card-infos">
        <div class="img-trophy">
        </div>
        <div class="score">
          <h2><span data-quizz-answer-target="score"><%= @gamingsession.score %></span> points</h2>
        </div>

    </div>
  </div>
  <% unless current_user %>
    <p class="text-div">Convertis tes <%= @gamingsession.score %> pts en bons de réductions chez nos partenaires ! </p>
    <div class="button_container">
      <div class="button-net">
        <%= link_to 'Sauvegarder mes points', new_user_session_path %>
      </div>
    </div>
  <% end %>

  <%# lien vers le sign-up/sign-in %>
  <%# donnée du user vs les records %>
    <h2>Tu as produit :</h2>
  <div class="chiffres-container">
    <div>
    </div>
    <div class="info-container">
      <div class="data-container">
        <div class="circle-container">
          <div>
            <h2><%= (@gamingsession.total_production)/7200%> Wh</h2>
          </div>
        </div>
        <div class="little-cercle">
            <i class="fa-solid fa-crown fa-xs couronne"></i>
          <div class="prod-record">
            <p><%= (@totalprodsession[0]["total_production"])/7200 %> Wh</p>
          </div>
        </div>
        <div class="production-title">
          <p>Production totale</p>
        </div>
      </div>
      <div class="data-container">
        <div class="circle-container">
          <div>
            <h2><%= (@gamingsession.max_production) %> W</h2>
          </div>
        </div>
        <div class="little-cercle">
            <i class="fa-solid fa-crown fa-xs couronne"></i>
          <div class="prod-record">
            <p><%= (@maxprodsession[0]["max_production"]) %> W</p>
          </div>
        </div>
        <div class="production-title">
          <p>Production instantanée max</p>
        </div>
      </div>
    </div>
    <div class="legend">
      <i class="fa-solid fa-crown fa-xs couronne"></i>
      <p>Record effectué sur le vélo</p>
    </div>
  </div>
  <span class="cache" data-quizz-answer-target="gsid"><%= @gamingsession.id %></span>
  <h2 class="h2-quizz">Quizz du jour :</h2>
  <% if current_user %>
    <div class= "quizz-card">
      <p>Lequel de ces appareils consomme le plus d’électricité par an ?</p>
      <div class="quizz-reponses">
        <div data-quizz-answer-target="frigo"class="quizz-choice-frigo">
          <p>Le réfrigérateur</p>
        </div>
        <div data-quizz-answer-target="lavelinge" class="quizz-choice-lavelinge-active" >
          <p>Le lave-linge</p>
        </div>
        <div data-quizz-answer-target="smartphone" class="quizz-choice-smartphone">
          <p>Le smartphone</p>
        </div>
        <div data-quizz-answer-target="tv" class="quizz-choice-tv">
          <p>La télévision</p>
        </div>
      </div>
    </div>
  <% else %>
    <div class= "quizz-card">
      <p>Lequel de ces appareils consomme le plus d’électricité par an ?</p>
      <div class="quizz-reponses">
        <div data-quizz-answer-target="frigo" data-action="click->quizz-answer#frigo" class="quizz-choice-frigo">
          <p>Le réfrigérateur</p>
        </div>
        <div data-quizz-answer-target="lavelinge"  data-action="click->quizz-answer#lavelinge" class="quizz-choice-lavelinge" >
          <div class="succes">
          <p>Tu as gagné 100 points</p>
          </div>
          <p>Le lave-linge</p>
        </div>
        <div data-quizz-answer-target="smartphone" data-action="click->quizz-answer#smartphone" class="quizz-choice-smartphone">
          <p>Le smartphone</p>
        </div>
        <div data-quizz-answer-target="tv" data-action="click->quizz-answer#tv" class="quizz-choice-tv">
          <p>La télévision</p>
        </div>
      </div>
    </div>
  <% end %>
  <%# comparatif %>
  <div class="comparatif-cardp" data-controller="return-images">
    <h3>Et concrètement ?</h3>
    <p>Compares ce que tu as produit avec la consommation d'électricité de quelques objets du quotidien.</p>


  <div class="container-comparatif">
    <div class="comparatif-cardleft">
      <div class="icone-compa"><span class="iconify" data-icon="bxs:fridge"></span>
      </div>
      <div class="card-content-left">
        <% @frigo = ((((550.0/((@gamingsession.total_production)/7200))*@gamingsession.session_duration)/60)/60).round %>
        <p><span class="text-compa"><%= @frigo %> h</span> de Vel-Watt pour alimenter un frigo <br>pendant <span class="text-compa">
        1 jour</span></p>
      </div>
    </div>
    <div class="comparatif-cardright">
      <div class="card-content-right">
        <% @tv = ((((250.0/((@gamingsession.total_production)/7200))*@gamingsession.session_duration)/60)/60).round %>
        <p><span class="text-compa"><%= @tv %> h</span> de Vel-Watt pour regarder la télévision pendant <span class="text-compa">1 h</span></p>
      </div>
      <div class="icone-compa"><span class="iconify" data-icon="bx:tv"></span>
      </div>
    </div>
    <div class="comparatif-cardleft">
      <div class="icone-compa"><span class="iconify" data-icon="mdi:washing-machine"></span>
      </div>
      <div class="card-content-left">
        <% @machine = ((((590/((@gamingsession.total_production)/7200))*@gamingsession.session_duration)/60)/60).round %>
        <p><span class="text-compa"><%= @machine %> h</span> de Vel-Watt<br> pour faire <span class="text-compa">1 cycle</span><br> de lave-linge</p>
      </div>
    </div>
    <div class="comparatif-cardright">
      <div class="card-content-right">
        <% @radiateur = ((((10000.0/((@gamingsession.total_production)/7200))*@gamingsession.session_duration)/60)/60).round %>
        <p><span class="text-compa"><%= @radiateur %> h</span> de Vel-Watt pour alimenter un radiateur pendant <span class="text-compa">1&nbsp;&nbsp;jour</span></p>
      </div>
      <div class="text-compa"><span class="iconify" data-icon="mdi:radiator"></span>
      </div>
    </div>
  </div>

    <div class="XXXX">
    </div>
</div>
<% if current_user %>
  <%= render "pages/menu" %>
  <% else %>
  <%= render "pages/menu_session" %>
<% end %>

app/views/historics/historique.html.erb
<div>
  <div >
    <h1>Historique de vos sessions</h1>
  </div>
  <div class="count-sessions">
    <div class="count">
      <h2><%= @gamingsessions.count %></h2>
    </div>
    <div class="sess">
      <p>sessions<p>
    </div>
  </div>
</div>

<div class="histo-container">
  <% @gamingsessions.each do |gs| %>
    <div class="histo-card">
      <div class="histo-text">
        <div class="date-div">
          <p class="date-text">Session du <span class="text-histo"><%= gs.date.strftime('%d-%m-%Y')%></span></p>
        </div>

        <div class="number-div">
          <p>Production totale : <span class="text-histo"><%= (gs.total_production)/7200%> Wh</span></p>
          <p>Score : <span class="text-histo"><%= gs.score%></span></p>
        </div>
      </div>
      <div class="see-session">
        <%= link_to gamingsession_path(gs.id) do %>
          <i class="fa-solid fa-bicycle"></i>
        <% end %>
      </div>

    </div>
  <% end %>
</div>

<%= render "pages/menu" %>

app/views/pages/_menu.html.erb
<div  class="menu-container">
  <div class="icone-menu">
      <%= link_to totaux_path do %>
        <i class="fa-solid fa-chart-line fa-xl <%= "prod" if request.path == "/totaux" %>"></i>
        <p class="<%= "prod" if request.path == "/totaux" %>">Résultats</p>
      <% end %>

      <%= link_to historique_path do %>
        <i class="fa-solid fa-clock-rotate-left fa-xl <%= "prod" if request.path == "/historique" %>"></i>
        <p class="<%= "prod" if request.path == "/historique" %>">Historique</p>
      <% end %>

      <%= link_to advantages_path do %>
        <i class="fa-solid fa-euro-sign fa-xl <%= "prod" if request.path == "/advantages" %>"></i>
        <p class="<%= "prod" if request.path == "/advantages" %>">Réductions</p>
      <% end %>
  </div>
</div>

app/views/pages/_menu_session.html.erb
<div class="menu-contain">
  <div class="navbar-elements-container">
    <%= link_to new_user_registration_path  do%>
      <div class="menu-element">
        <span class="iconify" data-icon="ic:baseline-app-registration"></span>
        <span>Inscription</span>
      </div>
    <% end %>

    <%= link_to new_user_session_path do %>
      <div class="menu-element">
        <span class="iconify" data-icon="carbon:login"></span>
        <span>Connexion</span>
      </div>
    <% end %>
  </div>
</div>